//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHSQLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_accounts
    {
        public int customer_id { get; set; }
        public string routing_number { get; set; }
        public string account_number { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
